name: Code Quality Check

on:
  push:
    branches:
      - main
      - workflow

jobs:
  pylint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint anybadge

    - name: Run pylint
      id: pylint
      run: |
        mkdir -p badges
        pylint_score=$(pylint app.py ./models/ pages/ utils/ --output-format=text | grep -oP 'Your code has been rated at \K([0-9.]+)')
        anybadge --value=$pylint_score --file=badges/quality.svg --label=Pylint --color=#76b947 --overwrite
    - name: Commit Changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add ./badges/*
        git commit -m "[Automatic]Update badges" || echo "Nothing to commit"
        git push
      continue-on-error: true

    - name: Notify if pylint fails
      if: failure()
      run: |
        echo "Pylint check failed. Please review the code quality."
