name: Code Quality Check

on:
  push:
    branches:
      - main

jobs:
  pylint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint

    - name: Run pylint
      id: pylint
      run: |
        pylint_score=$(find . -name "*.py" | xargs pylint --output-format=text | grep -oP 'Your code has been rated at \K([0-9.]+)')
        echo "pylint_score=$pylint_score" >> $GITHUB_OUTPUT

    - name: Update README Badge
      if: ${{ steps.pylint.outputs.pylint_score != '' }}
      run: |
        score=${{ steps.pylint.outputs.pylint_score }}
        badge_url="https://img.shields.io/badge/pylint-${score}-brightgreen"
        echo "Badge URL: $badge_url"
        echo "![pylint]($badge_url)" >> README.md

    - name: Commit Changes
      if: ${{ steps.pylint.outputs.pylint_score != '' }}
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add README.md
        git commit -m "Update pylint badge [skip ci]"
        git push origin HEAD:${{ github.ref }}
      continue-on-error: true

    - name: Notify if pylint fails
      if: failure()
      run: |
        echo "Pylint check failed. Please review the code quality."
